<a href="https://colab.research.google.com/github/Tuleen03/Week1-Intro-to-Python/blob/first-branch/Introduction_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PYTHON INTRODUCTION

#                                                      Table Of Content
1.introdution

     1.1 What is Python
     
2.Data types

     2.1 variables
     2.2 Numbers
     2.3 Strings
     2.4 Lists
     2.5 Dictionaries
     2.6 Tuples
     2.7 Sets
   
3.Comparison operators

4.If-Else statement

5.For Loop and While loop

6.Functions

7.Lambda functions

     7.1 Map()
     7.2 Filter()
   
8.File I/O

9.Pandas liberary introduction

10.Series

     10.1 From ndarray
     10.2 From dict
     10.3 From scalar value
     10.4 Series is ndarray-like
     10.5 Series is dict-like
     10.6 Vectorized operations and label alignment with series
   
11.Data frames

     11.1 From dict of series or dicts
     11.2 from dict of ndarrays/lists
     11.3 from a list of dicts
     11.4 from a list of tuples
     11.5 Alternate constructors
     11.6 Column selection, addition, deletion
     11.7 Indexing/ selection
     11.8 Data alignment
     11.9 transposing

# 1. Introduction

## 1.1 What is python

Guido Van Rossum developed the Python language in the late 1980s. In contrast to other popular languages such as C, C++, Java, and C#, Python strives to provide a simple but powerful syntax.It is open source general purpose language with great interactive environment.It provides all the three types of programming features Object Oriented, Procedural and Functional.It is used by many of the most highly productive professional programmers.Moreover, Python can also become a common language for production of web based analytics product. A few of the places that use Python extensively are Google, the New York Stock Exchange, Industrial Light,Magic etc.
#### Important features of Python:
 -  Built-in high level data types: strings, lists, dictionaries, etc.
 -  The usual control structures: if, if-else, if-elif-else, while, plus a powerful collection iterator (for).
 -  Multiple levels of organizational structure: functions, classes, modules, and  packages. These assist in organizing code. An excellent and large example is the Python standard library.
 - Compile on the fly to byte code -- Source code is compiled to byte code without a separate compile step. Source code modules can also be "pre-compiled" to byte code files.
 - Object-oriented -- Python provides a consistent way to use objects: everything is an object. And, in Python it is easy to implement new object types (called classes in object-oriented programming).
 - Extensions in C and C++ -- Extension modules and extension types can be written by hand. There are also tools that help with this, for example, SWIG, sip, Pyrex

# 2. Data types

There are various data types in Python. Some of the important types are listed below.

## 2.1 Variables

 - Python variables do not need explicit declaration to reserve memory space.
 - The declaration happens automatically when you assign a value to a variable.
 - The equal sign = is used to assign values to variables.
  
  Some examples are given as follows:

In [169]:
area = 200.30  #float type variable
Distance = 100 #integer type variabe
name = 'Sara' #string type variable
x = "Hello"
y = 10.05

#print all values
print(area)
print(Distance)
print(name)
print(x)
print(y)

200.3
100
Sara
Hello
10.05

In [170]:
x=5.0
y=3
T= 'Tuleen'

print (x)
print (y)
print (T)

5.0
3
Tuleen

## 2.2 Numbers

 - This data type store numeric values
 - Numbers are immutable data types (Immutable data types means values cannot be changed after it is created)

  Some examples are given as follows:

In [171]:
5 #integer

5

In [172]:
3

3

In [173]:
10+10 #integer

20

In [174]:
4+4

8

In [175]:
5.5+5.5 #float

11.0

In [176]:
5.1+3.2

8.3

In [177]:
5**2 #exponent

25

In [178]:
2**2

4

## 2.3 Strings

 - Strings in Python are identified as a contiguous set of characters represented in the quotation marks.
 - Python allows either pair of single or double quotes.
 - Strings are immutable.
 - Python doesn't support Char data type.It will beas string of length one in python.

In [179]:
Course="Artificial Intelligence"
name='Sara'
print(name, Course)

Sara Artificial Intelligence

In [180]:
course = 'IAT'
name = 'TULEEN'

print('hello',name,'from',course)

hello TULEEN from IAT

### Access values in strings

 - we can access a specific character or range of characters from strings.
 - Subsets of strings can be taken using the slice operator [] and [:] with indexes starting from 0.

 Some examples are listed below:

In [181]:
stringVariable = 'Hello World'

print("stringVariable[0]:", stringVariable[0])
print("stringVariable[1:5]:", stringVariable[1:5])

stringVariable[0]: H
stringVariable[1:5]: ello

In [182]:
string1 = "so many words in a sentence"

print("first element of a string, in position 1", string1[0])
print("remaining elements of a string", string1[1:27])

first element of a string, in position 1 s
remaining elements of a string o many words in a sentence

### Updating string

 - Value of string can be changed or updated by assigning a new value to it.
 - New value must have same data type as previous value.
 - For this purpose '+' operator is used as follows:

In [183]:
stringVariable ="Hello World "
stringVariable = stringVariable[:6]+"Python"


print("updated string:",stringVariable)

updated string: Hello Python

In [184]:
string="how are you?"
string = string[:14]+ " Im good thanks"
print("new string:", string)

new string: how are you? Im good thanks

### Delete string

 - we can delete the value of string by just deleteing its object.
 - 'del' keyword is used for this purpose

  It would be cleared by using following example:

In [185]:
stringVariable ="Hello World "
print(stringVariable)
del stringVariable
print(stringVariable)

Hello World

NameError: name 'stringVariable' is not defined

### String special operators

 - some special operators are used in Python to perform different opertions.
   These are given below:

#### String Concatenation

 - To concatenate the strings we used '+' operator.

    Following are the examples of concatenation:

In [ ]:
stringvalue1="machine"
stringvalue2="learning"
print(stringvalue1+stringvalue2)

In [ ]:
stringvalue1="5"
stringvalue2="5"
print(stringvalue1+stringvalue2)

#### Repitition

 - '*' symbol is used for repitition.

In [ ]:
stringvalue="Assignment"
print(stringvalue*2)

In [ ]:
stringvalue="Assignment"
stringval2=(stringvalue*2)
print(stringval2)

#### Use of [] symbol

 - '[]'symbol give the character of string at given index.

In [ ]:
Stringvalue="Machine Learning"
print(Stringvalue[1])

In [ ]:
Stringvalue="Machine Learning"
print(Stringvalue[1])
print(Stringvalue[0:])

#### Use of [:] symbol

 - [:] is used to get substring from string.

In [ ]:
stringvalue="Hello"
print(stringvalue [1:3])

In [ ]:
stringvalue="lettuce"
print(stringvalue [1:3])
print(stringvalue [0:1])

#### use of 'in'

 - 'in' is used to check the existance of character in string.
 - It returns TRUE if given character exist in string,otherwise FALSE.

In [ ]:
Stringvalue="Hello"
print('H' in Stringvalue)

In [ ]:
string = "what is a string?"
print("w" in string)
print("z" in string)

#### Use of "not in"

 - 'not in' returns true if given character is not in string,otherwise false.

In [ ]:
Stringvalue="Hello"
print('G' not in Stringvalue)
print('o' not in Stringvalue)

### String formatting operator

 - Python uses C-style string formatting to create new, formatted strings.
 - The "%" operator is used to format in print statement.

See following examples:

In [ ]:
print("My name is %s and weight is %d kg!" % ("Sara", 21))

In [ ]:
print("hello %s how did you do on your exam? " % ("lea"))

## 2.4 Lists

 - Multiple types of data can be stored in a list.
 - A list contains items separated by commas and enclosed within square brackets [].
 - Individual elements of a list can be changed
 - list indices start with 0 just like arrays.

In [ ]:
list1 = [ 'Mary', 2000 ]

print(list1) # Prints complete list
list2 =["laila", 4000]
print (list2)

### Accessing values in list

 - Square brackets are used to access the values of a list
 - We can access specific values or range of values from a list

In [ ]:
list1 = [ 'Physics' , 'Chemistry' , 1857, 3290]
list2 = [1,2,3,4,5,6,7]

print("list1[0]: ", list1[0])
print("list2[1:5]: ", list2[1:5])
print("list2 everything", list2[0:])

### Updating list

 - Value of string can be changed or updated by assigning a new value to it.
 - we can update single or multiple elements of a list by giving slice on left hand of the assignment operator.
 - we can also update list by using append() function.

In [ ]:
list1=["dell","Hp","Apple"]
list1[1]="samsung"
print(list1)

list1.append('acer')
print(list1)

list3=["hahn","jen", 5]
list3.append('leo')
print(list3)

### Delete List Element

- we can delete the element of list by using del keyword or remove()function.
- 'del' keyword is used when you know the position or index of element to be deleted.
- remove() function can be used when you don't know the postion of element to be removed.

  It would be cleared by using following example:

In [ ]:
list1=["dell","Hp","Apple"]
print (list1) # Prints complete list
del list1[1]
print("After deleting the value ")
print (list1)



list3=["hahn","jen", 5]
print (list3)
list1.remove("Apple")
print (list3)
print (list1)

In [ ]:
list1=["dell","Hp","Apple"]
print (list1) # Prints complete list

list1.remove('Hp')
print("After deleting the value ")
print (list1)

## 2.5 Dictionaries

 - Dictionary is an unordered set of key: value pairs, with the requirement that the keys are unique (within one dictionary).
 - Each key is seperated by colon(:) from its value.
 - Each item is seperated with comma(,).
 - A pair of braces creates an empty dictionary: {}.
 - Python's dictionaries are kind of hash-table type.
 - A dictionary key can be almost any Python type, but are usually numbers or strings. Values, on the other hand, can be any       arbitrary Python object.
 - Dictionaries are enclosed by curly braces ({ }) and values can be assigned and accessed using square braces ([])
 - Dictionaries have no concept of order among elements. It is incorrect to say that the elements are "out of order"; they are simply unordered

## Accessing value in dictionary

- Square brackets [] along with the key are used to access its value.

In [ ]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1['Department'])
print(dict1['Batch'])

### Updating Dictionary

- we can update values in dictionary
- we can also add new values in dictionary

Some examples are given below:

In [ ]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1)
dict1['Batch']="S23"
dict1['Name']="leo"
print(dict1)

### Delete Dictionary element

- we can delete elements of dictionary as well as complete content of dictionary.
- To delete single element del keyword is used.
- clear() function  is used to remove complete dictionary.

 Some examples are as follows:

In [ ]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1)

del dict1['Batch']
del dict1['Department']
print(dict1)

In [ ]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
dict1.clear()
dict2 = {'Name':"leo" , "Name2" : "joe"}
print("dict2 before edit",dict2)
dict2.clear()
print("dict2 after clear fucntion", dict2)

## 2.6 Tuples

 - A tuple is another sequence data type that is similar to the list.
 - A tuple consists of a number of values separated by commas. Unlike lists, however, tuples are enclosed within parenthesis.
 - The main difference between lists and tuples are − Lists are enclosed in brackets ( [ ] ) and their elements and size can be  changed, while tuples are enclosed in parentheses ( ( ) ) and cannot be updated. Tuples can be thought of as read-only lists.   
 - It can also have multiple data type values.

  For example:

### Accessing values in Tuples

- Square brackets [] along with the index are used to access its value.

In [ ]:
tuple1 = ( 'simon','sara' , '20', 'saira40')

print (tuple1)
print(tuple1[1:3])

tuple2 = ( 'x','y' , 'z', 'e')
print(tuple2[0:])

### Updating Tuples

- Tuples are immutable means we cannot change the value of tuple.
- It is read only.
- we are able to take portions of tuples to make a new tuple.

In [ ]:
tuple1=('sun','mon','tue','wed','thur','fri' , 'sat')
tuple2=(1,2,3,4,5,6,7)
print(tuple1)
print(tuple2)
tuple3=(tuple1+tuple2)
print(tuple3)

tuple4 = ('January', 'February', 'March', 'April', 'May', 'June', 'July')
tuple5= (31, 28, 31, 30, 31, 30, 31)
print(tuple4)
print(tuple5)

tuple6 = tuple4 + tuple5
print(tuple6)

### Delete tuple elements

- we cannot delete single elements of tuple because they cannot be updated.
- To delete entire elements del keyword is used.

 Some examples are as follows:

In [ ]:
tuple1=('sun','mon','tue','wed','thur','fri' , 'sat')
tuple2=(1,2,3,4,5,6,7)
print(tuple1)
print(tuple2)
del(tuple1)
print(tuple1)

In [ ]:
tuple4 = ('January', 'February', 'March', 'April', 'May', 'June', 'July')
tuple5= (31, 28, 31, 30, 31, 30, 31)
print(tuple4)
print(tuple5)

tuple6 = tuple4 + tuple5
print(tuple6)
del(tuple5)
tuple6 = tuple4 + tuple5
print(tuple6)

# 2.7 Sets

 - A set is an unordered collection in which each value occurs at most once.
 - You can use curly braces to give an expression whose value is a set.
 - Python prints sets using curly braces.
 - Every value in a set is immutable but the set itself is immutable we can add o remove items from it.
 - Sets can be used to perform mathematical operations like union,intersection,etc
 - Empty set will be written as {}.
 - We can also make a set from a list using set() function.
 - Data type can be found using type() function.
 - add() is used to add single value, update() is used for adding multiple values.
 - update() function can take tuple,string,list or other set as argument.
 - discard() and remove() are used to delete specific item from list.
 - discard() will not raise an error if item doesn't exist.
 - remove() will raise an error if item doesn't exist in set.
 - The cardinality of a set S is the number of elements in the set.
 - In Python, the cardinality of a set is obtained using the function len(·).

In [ ]:
#list
list1=[1,2,3,4,5]

print(type(list1))

my_set=set(list1)

print(type(my_set))

#set of integers
my_set={1,2,3}
print(my_set)

#set of mixed data types
my_set={1, "Hello"}

#adding a single value
my_set.add("D")

#adding multiple values
my_set.update(list1)
print(my_set)


my_set.discard('G') #it will not raise an error
my_set.remove('G') #it will raise an error

In [ ]:
list1 = [1, 2, 3, 4, 5]

list1[0] = 10
list1[2] = 'A'
list1[-1] = 100

my_set = set(list1)

print(type(list1))
print(type(my_set))

my_set = {1, 2, 3}
print(my_set)

my_set = {1, "Hello"}

my_set.add("D")

my_set.update(list1)
print(my_set)

my_set.discard('G')

# Uncommenting the next line will result in a KeyError
# my_set.remove('G')

# 3.Comparison Operators

 - Comparison operators are used to compare values and return TRUE/FALSE according to the situation.
 - Python defines the following comparison operators:

### Less than operator  (<)

In [ ]:
10<17

### Less than equal to operator (<=)

In [ ]:
15<=10

### Equal to operatoe (==)

In [ ]:
16==16

In [ ]:
"Sara"=="sara"

In [ ]:
"ALI"=="ALI"

### Not equal to operator (!=)

In [ ]:
3!=5

### OR Operator

In [ ]:
(10==10)or(10<17)

### And operator

In [ ]:
(10==10)and (10<17)

In [ ]:
result_equal = 5 == 5
print(result_equal)

result_not_equal = 5 != 10
print(result_not_equal)

result_greater_than = 10 > 5
print(result_greater_than)

result_less_than = 5 < 10
print(result_less_than)

result_greater_than_equal = 10 >= 10
print(result_greater_than_equal)

result_less_than_equal = 5 <= 10
print(result_less_than_equal)

# 4.If else statement

 - The if–else is used to make choices in Python code.
 - This is a compound statement.
 - The syntax is:
 - if c o n d i t i o n
          action −1
  else :
          action −2
 - The indentation is required

In [ ]:
x = 3
if x > 0:
    print(" sunday is wonderful")
else :
    print(" Monday is Good ")

In [ ]:
x = 5

if x > 0:
    print("The weather is sunny!")
else:
    print("It's a bit cloudy today.")

In [ ]:
if 25 % 2:
  print("Even")
else:
  print("Odd")

In [ ]:

if 25 % 2:
  print("even")
else:
  print("odd")

if 32 % 7:
  print("there is remainder")
else:
    print("no remainder")

# 5.For and while loop

- Python has for and while loop for iteration,used when we want to perfrom a specific task repeatedly.

### For loop

- The for statement is used to iterate over the elements of a sequence.
- It's traditionally used when you have a piece of code which you want to repeat n number of time.
- The syntax of a for loop is:

    for item in list :
      a c t i o n
- As usual, the action consists of one or more statements, all at the same indentation level. These statements are also known as the body of the loop. The item is a variable name, and list is a list.
- Execution of the for loop works by setting the variable successively to each item in the list, and then executing the body each time.

  Here is a simple example:

In [ ]:
for i in [2 , 4 , 6 , 0]:
    print(i)

In [ ]:
for counter in range(1, 6):
    print(counter)

In [ ]:
word = "sara"
for letter in word:
    print(letter)

In [ ]:
for counter in range(5, 0, -1):
    print(counter)

In [ ]:
word = "Simon Fraser University"
for letter in word:
    print (letter)

### While loop

In [ ]:
a=0
while a < 10:
  a=a+1
  print(a)

In [ ]:
a=-1
while a < 10:
  a=a+1
  print(a)

In [ ]:
a = -2
while a < 10:
    a += 1
    print(a)

# 6.Functions

 - You use functions in programming to bundle a set of instructions that you want to use repeatedly or that, because of their  complexity, are better self-contained in a sub-program and called when needed.                                 
 - Function is a piece of code written to carry out a specified task.
 - There are three types of functions in Python:
 - Built-in functions, such as help() to ask for help, min() to get the minimum value, print() to print an object.
 - User-Defined Functions (UDFs), which are functions that users create to help them out.
 - Anonymous functions, which are also called lambda functions because they are not declared with the standard def keyword.
 - The syntax is:

   def functionname(parameters)
    
   "function_docstring"
   
   function_suite
   
   return [expression]

In [ ]:
def my_function(name):
  #This prints a passed string into this function
    print(name)
    return;

#Now you can call my_function
my_function("Mary")

def function3(a,b):
  x=a*b
  print(x)
  return;
function3(2,3)

# 7.Lambda Functions

 - The creation of anonymous functions at runtime,using a construct called "lambda"
 - A lambda function is a small anonymous function.
 - A lambda function can take any number of arguments, but can only have one expression.
 - Lambda function does not include return statement,it always contains an expression which is returned.
 - You might want to use lambdas when you don’t want to use a function twice in a program.

   some examples are given:

In [ ]:
#Normal Function
def f (x):
  return x**2
print(f(8))

In [ ]:
times3 = lambda var:var*3
times3(10)

#lamba expressions : another way to write a function in line

x = 2
result = (lambda x: 2 * x)(x)
print(result)

In [ ]:
add = lambda x, y: x + y

print(add(3, 5))

## 7.1 Map()

 - Map() function is used with two arguments.Just like: r=map(func,seq)
 - The first argument func is function name and the second is a sequence(list etc)
 - Map functions expects a function object and any number of iterables like list, dictionary, etc.
 - It executes the function_object for each element in the sequence and returns a list of the elements modified by the function  object.

   Example:

In [ ]:
sentence = "It is raining cats and dogs"
words = sentence.split()
print(words)

lengths= map(lambda word :len(word), words)

list (lengths)
numbers = [1, 2, 3, 4, 5]
result = map(lambda x: x * 2, numbers)
result_list = list(result)
print(result_list)

## 7.2 Filter()

 - The filter() method filters the given iterable with the help of a function that tests each element in the iterable to be true or not.
 - The syntax of filter() method is:
      filter(function, iterable)
 - The filter() method takes two parameters:

      1)function - function that tests if elements of an iterable returns true or false If None, the function defaults to Identity function - which returns false if any elements are false
      
      2)iterable - iterable which is to be filtered, could be sets, lists, tuples, or containers of any iterators
 - The filter() method returns an iterator that passed the function check for each element in the iterable.

In [ ]:
# list of alphabets
alphabets = ['a', 'b', 'd', 'e', 'i', 'j', 'o']

# function that filters vowels
def filterVowels(alphabet):
    vowels = ['a', 'e', 'i', 'o', 'u']

    if(alphabet in vowels):
        return True
    else:
        return False

for i in filter(filterVowels, alphabets):
     print(i)

In [ ]:
alphabets = ['a', 'b', 'd', 'e', 'i', 'j', 'o']

vowels = filter(lambda x: x in ['e', 'o', 'u'], alphabets)

for i in vowels:
    print(i)

In [ ]:
# random list
randomList = [1, 'a', 0, False, True, '0']

filteredList = filter(None, randomList)

print('The filtered elements are:')
for element in filteredList:
    print(element)

In [ ]:
randomList = [1, 'a', 0, False, True, '0']

filteredList = filter(lambda x: x, randomList)

print('The filtered elements are:')
for element in filteredList:
    print(element)

In [ ]:
ages = [5, 12, 17, 18, 24, 32]

def myFunc(x):
  if x < 18:
    return False
  else:
    return True

adults = filter(myFunc, ages)

for x in adults:
  print(x)

In [ ]:
ages = [5, 12, 17, 18, 24, 32]

myFunc = lambda x: x >= 18

adults = filter(myFunc, ages)

for x in adults:
    print(x)

# 8.File I/O

 - In this section we will cover basic I/O functions.

## Reading input from keyboard

 -  There are two functions in Python that you can use to read data from the user:raw_input and input
 -  You can store the results from them into a variable
 -  If the input function is called, the program flow will be stopped until the user has given an input and has ended the input  with the return key. The text of the optional parameter, i.e. the prompt, will be printed on the screen.

 Let's have a look at the following example:

In [ ]:
name = raw_input("What's your name? ")
print("Nice to meet you " + name + "!")

name = input("Please enter your name: ")
print("Nice to meet you, " + name + "!")

In [ ]:
age = raw_input("What's your age? ")
print("your age is " + age + "!")

age = input("How old are you? ")
print("Interesting! You're " + age + " years old.")

In [ ]:
string=raw_input("enter your university....")
print(string)
string = input("Enter your university: ")
print(string)

## I/O From or to text file

 - In this scenario, we will read and write to a text file.
 - we can open files in different modes.

## Read only mode

 - r opens a file in read only mode.
 - The file pointer is placed at the beginning of the file.
 - This is the default mode.

In [ ]:

file = open("hello.txt", "r")
str=file.read();
print(str)
file.close()

In [ ]:
file = open("file.txt", "r")
content = file.read()
print(content)
file.close()

## Read and write mode

 - r+ opens a file in read and write mode.
 - The file pointer placed at the beginning of the file

In [ ]:
# Open a file
file = open("hello.txt", "r+")
str = file.read(10);
print "Read String is : ", str
# Close opend

In [ ]:
# Open another file
file = open("file.txt", "r+")
str_value = file.read(10)
print("Read String is:", str_value)
# Close the opened file
file.close()

## Write mode only

 - w opens a file in write mode only.
 - Overwrites the file if the file exists. If the file does not exist, creates a new file for writing

In [ ]:
file = open('write.txt','w')
file.write("This is the write command")
file.write("It allows us to write in a particular file")
file = open('write.txt','r')
str=file.read()
print(str)
file.close()

In [ ]:
file = open('write.txt', 'w')

file.write("Welcome to Python File Handling\n")  # Updated text
file.write("This is an example of write mode\n")  # Updated text

file.close()

# Open the file for reading
file = open('write.txt', 'r')
content = file.read()
print(content)
file.close()

## Append mode

 - a opens a file in append mode.
 - The file pointer is at the end of the file if the file exists.
 - That is, the file is in the append mode. If the file does not exist, it creates a new file for writing.

In [ ]:
file = open('write.txt','a')
file.write("This will add this line")
file = open('write.txt','r')
str=file.read()
print(str)
file.close()

In [ ]:
# Open a file in append mode ('a')
file = open('append_file.txt', 'a')

# Write content to the file
file.write("This is appended content.\n")
file.write("It goes to the end of the file.\n")

# Close the file
file.close()

# Open the file for reading
file = open('append_file.txt', 'r')

# Read and print the content
content = file.read()
print(content)

# Close the file
file.close()

## Append and read mode

 - a+ opens a file in append and read mode.
 - The file pointer is at the end of the file if the file exists. The file opens in the append mode. If the file does not exist,    it creates a  new file for reading and writing.

In [ ]:
file = open('hello.txt','a+')
file.write("MSCS From comsats university")
file.close()
file = open('hello.txt','r')
str=file.read()
print(str)
file.close()

In [ ]:
file = open('append_and_read_file.txt', 'a+')
file.write("This is appended content.\n")
file.write("It goes to the end of the file.\n")
file.close()

file = open('append_and_read_file.txt', 'r')
content = file.read()
print(content)
file.close()

## File Position

 - tells() method tells the current position within the file.
 - seek() method changes the current file method.
 - Following is the syntax for seek() method:    fileObject.seek(offset[, whence])

In [ ]:
f = open('hello.txt',"r+")
str=f.read(20);
print("read string is :",str)

position=f.tell();
print("current file position is :",position)

position=f.seek(5);
str=f.read(10);
print("again read string is :",str)
f.close()

In [ ]:
f = open('append_and_read_file.txt', 'r+')
str_value = f.read(20)
print("Read string is:", str_value)

position = f.tell()
print("Current file position is:", position)

position = f.seek(5)
str_value = f.read(10)
print("Again read string is:", str_value)

f.close()

# 9.Pandas Introduction

Pandas is an open-source Python Library providing high-performance data manipulation and analysis tool using its powerful data structures. The name Pandas is derived from the word Panel Data – an Econometrics from Multidimensional data. In 2008, developer Wes McKinney started developing pandas when in need of high performance, flexible tool for analysis of data.

Prior to Pandas, Python was majorly used for data munging and preparation. It had very less contribution towards data analysis. Pandas solved this problem. Using Pandas, we can accomplish five typical steps in the processing and analysis of data, regardless of the origin of data — load, prepare, manipulate, model, and analyze.

Python with Pandas is used in a wide range of fields including academic and commercial domains including finance, economics, Statistics, analytics, etc.

#### Key Features of Pandas

-  Fast and efficient DataFrame object with default and customized indexing.
-  Tools for loading data into in-memory data objects from different file formats.
-  Data alignment and integrated handling of missing data.
-  Reshaping and pivoting of date sets.
- Label-based slicing, indexing and subsetting of large data sets.
- Columns from a data structure can be deleted or inserted.
- Group by data for aggregation and transformations.
- High performance merging and joining of data.
- Time Series functionality.

Pandas deals with the following three data structures:
- Series
- DataFrame
- Panel

These data structures are built on top of Numpy array, which means they are fast.

# 10.Series

- The Series is a one-dimensional array that can store various data types, including mix data types.
- The row labels in a Series are called the index.
- Any list, tuple and dictionary can be converted in to Series using ‘series’ method
- Basic method to create a series: s = pd.Series(data, index = index)
- Series is size immutable.

In [ ]:
import pandas as pd
s = pd.Series([1, 'Lahore', 2, 3, 'Happy Eating!'])
s

In [ ]:
import pandas as pd

# Creating a Series with mixed data types and custom index
data = {'a': 1, 'b': 'Lahore', 'c': 2, 'd': 3, 'e': 'Happy Eating!'}
custom_index = ['a', 'b', 'c', 'd', 'e']

s = pd.Series(data, index=custom_index)

# Displaying the Series
print(s)

## 10.1 Series creation from ndarray

- Index must be of same length as data. If no index is passed, it will automatically be [0, ..., len(data) - 1]

In [ ]:
first_series = pd.Series([1,2,4,8,16,32,64])
print(type(first_series))
print(first_series)

In [ ]:
import pandas as pd

second_series = pd.Series([2, 4, 8, 16, 32, 64, 128])
print(type(second_series))
print(second_series)

In [ ]:
import numpy as np
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s)
print('-'*50)
print(s.index)

In [ ]:

random_series = pd.Series(np.random.randn(5), index=['p', 'q', 'r', 's', 't'])
print(random_series)
print('-' * 50)
print(random_series.index)

## 10.2 Series creation from dict

- If Data is a dictionary, if index is passed the values in data corresponding to the labels in the index will be pulled out, otherwise an index will be constructed from the sorted keys of the dict.

In [ ]:
d = {'a': 100., 'b': 200., 'c': 300.}
pd.Series(d)

In [ ]:
data = {'abc': 1, 'def': 2, 'xyz': 3}
pd.Series(data)

In [ ]:
my_dict = {'apple': 5, 'banana': 10, 'orange': 8}
series_from_dict = pd.Series(my_dict)

print(series_from_dict)

## 10.3 Series creation from a scalar value

- Index must be provided. The value will be repeated to match the length of the index

In [ ]:
pd.Series(5, index = ['a', 'b', 'c'])

In [ ]:
 x = pd.Series(3, index=['a', 'b', 'c', 'd'])
x

In [ ]:
scalar_series = pd.Series(10, index=['x', 'y', 'z'])
scalar_series

In [ ]:
value_series = pd.Series(7, index=['p', 'q', 'r'])
print(value_series)

scalar_data = pd.Series(15, index=['m', 'n', 'o'])
print(scalar_data)

custom_series = pd.Series(8, index=['p', 'q', 'r', 's'])
print(custom_series)

In [ ]:
value_series

In [ ]:
scalar_data

In [ ]:
custom_series

## 10.4 Series is ndarray-like

- Series acts similar to a numpy array, and is valid arguments to most numpy functions.
- Slicing also slices the index
- Short Intro, back to this later

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s)

In [ ]:
random_series = pd.Series(np.random.randn(5), index=['p', 'q', 'r', 's', 't'])
print(random_series)

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s.iloc([2,1,4]))

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s[:3])

In [ ]:
s = pd.Series(np.random.randn(5), index=['p', 'q', 'r', 's', 't'])

print(s[:3])

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s[[3,2,1]])

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
np.exp(s)

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s['b']

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s['b']=12.
s

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
'e' in s

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
'f' in s

## 10.5 Series is dict-like

- A Series is like a xed-size dict in that you can get and set values by index label

In [ ]:
s = pd.Series([1, 2, 3, 4])
s.to_dict()

In [ ]:
a = pd.Series([4, 6, 8, 10])
a.to_dict()

## 10.6 Vectorized operations and label alignment with Series

- When doing data analysis,as with the row NumPy arrays looping through series value by value is usually not necessary.
- Series can also be passed into most NumPy method expecting an ndarray.
- NumPy and Pandas generalize arithmetic operations so that we can easily and quickly perform the same operation on many array elements. For example:

In [ ]:
import numpy as np
x = np.array([2, 3, 5, 7, 11, 13])
x * 2

In [ ]:
import numpy as np
y = np.array([5, 6, 7, 12, 15, 30])
y * 2

In [ ]:
data = ['saima', 'aisha', 'faiza', 'saira']
[s.capitalize() for s in data]

In [ ]:
d = ['leo','joe','lee']
[l.capitalize() for l in d]

# 11.Data Frames

- A DataFrame is a two dimensional object that can have columns with potential different types. Different kind of inputs include dictionaries, lists, series, and even another DataFrame.
- It is the most commonly used pandas object.
- You can create a series from:
    - Dict of 1D ndarrays, lists, dicts, or Series
    - 2-D numpy array
    - A list of dictionaries
    - A Series
    - Another Dataframe
  
- index/ columns is a list of the row/ column labels. If you pass an index and/ or columns, you are guarenteeing the index and /or column of the df.
- If you do not pass anything in, the input will be constructed by "common sense" rules

In [ ]:
dates = pd.date_range('20130101',periods=6)
dates

In [ ]:
date_range = pd.date_range('20220101', periods=8)
print(date_range)

## 11.1 Dataframe creation from dict of series or dicts

 - The index of the resulting DataFrame will be the union of the indices of the various Series. If there are any nested dicts, these will be converted to Series.
 - If no columns are passed, the columns will be the sorted list of dict keys.

In [ ]:
# Create a dictionary of series
d = {'one': pd.Series([1,2,3], index = ['a', 'b', 'c']),
'two': pd.Series(list(range(4)), index = ['a','b', 'c', 'd'])}
# Columns are dictionary keys, indices and values obtained from series
df = pd.DataFrame(d)
# Notice how it fills the column one with NaN for d
print(df)

In [ ]:
x = {'age': pd.Series([20,25,30], index = ['leo', 'joe', 'mic']),
'position': pd.Series(list(range(4)), index = ['leo','joe', 'mic', 'ron'])}
# Columns are dictionary keys, indices and values obtained from series
df = pd.DataFrame(x)
print(df)

In [ ]:
 d = {'col1': [1, 2], 'col2': [3, 4]}
 df = pd.DataFrame(data=d)
 df

## 11.2  Dataframe creation from dict of ndarrays/lists

 - The ndarrays must all be the same length.
 - If an index is passed, it must clearly also be the same length as the arrays. If no index is passed, the result will be range(n), where n is the array length.

In [ ]:
d = {'one' : [1., 2., 3., 4.], 'two' : [4., 3., 2., 1.]}
pd.DataFrame(d)

In [ ]:
x = {'num1' : [3., 4., 5., 6.], 'num2' : [6., 5., 2., 1.]}
pd.DataFrame(x)

In [ ]:
df2 = pd.DataFrame(np.random.randint(low=0, high=10, size=(5, 5)), columns=['a', 'b', 'c', 'd', 'e'])
df2

## 11.3 Dataframe creation from a list of dicts

In [ ]:
data = [{'a':10,"b":20},{'a':5,'b':10,'c':20}]
pd.DataFrame(data)

In [ ]:
data = [{'a':10,"b":20,"c":30},{'a':5,'b':10,'c':20}]
pd.DataFrame(data)

In [ ]:
data = [{'x':12,"y":25},{'x':10,'y':15,'z':20}]
pd.DataFrame(data)

## 11.4 Dataframe creation from a dict of tuples

 - You can automatically create a multi indexed by passing a tuple dictionary.

In [ ]:

df = pd.DataFrame({'Initial': ['C','A','M'], 'Sex': ['M', 'F', 'F'], 'Age': [49, 39, 19]})
#df = df[['Initial', 'Sex', 'Age']]
df

In [ ]:
data = [('p1', 't1', 1, 2),('p1', 't2', 3, 4),('p2', 't1', 5, 6),('p2', 't2', 7, 8),('p2', 't3', 2, 8)]

df = pd.DataFrame(data)
df

In [ ]:
data = [('p3', 't4', 10, 20), ('p3', 't5', 30, 40), ('p4', 't4', 50, 60), ('p4', 't5', 70, 80), ('p4', 't6', 20, 80)]

df = pd.DataFrame(data)
df

## 11.5 Alternate constructors

### Dataframe.from_dict

 - Dataframe.from_dict takes a dict of dictsor a dict of array like sequences and returns a Dataframe.
 - It operates like the dataframe constructor except for the orient parameter which is coulmn by default,but which can be set to index in order to use the dict keys as row labels.

In [ ]:
data = {"X": {'a': 1, 'b': 2, 'c': 3}, "Y": {'d': 4, 'e': 5, 'f': 6}, "Z": {'g': 7, 'h': 8, 'i': 9}}

df = pd.DataFrame.from_dict(data, orient="index").fillna(0).astype(int)
df

In [ ]:
data = {"X": {'a': 10, 'b': 20, 'c': 30}, "Y": {'d': 40, 'e': 50, 'f': 60}, "Z": {'g': 70, 'h': 80, 'i': 90}}

df = pd.DataFrame.from_dict(data, orient="index").fillna(0).astype(int)
df

### Dataframe.from_records

- Dataframe.from_records take a list of tuples or an ndarray with structured dtype.
- Works analogously to the normal dataframe constructor,except that index may be aspecific field of the structured dtype to use as the index.for example:

In [ ]:
sales = [('Jones LLC', 150, 200, 50),
     ('Alpha Co', 200, 210, 90),
     ('Blue Inc', 140, 215, 95)]
labels = ['account', 'Jan', 'Feb', 'Mar']
df = pd.DataFrame.from_records(sales, columns=labels)
df

In [ ]:
university_data = [('UniversityA', 180, 220, 80),
                   ('UniversityB', 250, 200, 100),
                   ('UniversityC', 160, 180, 70)]

labels = ['university', 'Jan', 'Feb', 'Mar']

university_df = pd.DataFrame.from_records(university_data, columns=labels)
university_df

### Dataframe.from_items

- Convert (key, value) pairs to DataFrame. The keys will be the axis index (usually the columns, but depends on the specified orientation). The values should be arrays or Series.

In [ ]:
import pandas as pd
# Use a list of dictionaries instead of from_items
df = pd.DataFrame([{'A': 1, 'B': 4}, {'A': 2, 'B': 5}, {'A': 3, 'B': 6}])
df

In [ ]:
import pandas as pd
df=pd.DataFrame.from_dict([('A',[1,2,3]),('B',[4,5,6])])
df

In [ ]:
df=pd.DataFrame.from_dict([('A',[1,2,3]),('B',[4,5,6])])
df

## 11.6 Column selection,addition,deletion

 - You can treat a DataFrame semantically like a dict of like-indexed Series objects. Getting, setting, and deleting columns works with the same syntax as the analogous dict operations:

In [186]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','a']) # you can adress column by index
df

   a  a
0  1  2
1  3  4
2  5  6

In [189]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','a'])
df.columns = ['a','b']  # rename column
df

   a  b
0  1  2
1  3  4
2  5  6

In [190]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','b'])
del df['b']   # delete column
df

   a
0  1
1  3
2  5

In [191]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','b'])
del df['a']   # delete column
df

   b
0  2
1  4
2  6

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','b'])
df['c']='2'   #add new column c and fill with 2
df

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','b'])
df['a']='10'   #add new column c and fill with 2
df

### 11.7 Indexing / seletion

- Row selection, for example, returns a Series whose index is the columns of the DataFrame:
- Pandas now supports three types of Multi-axes indexing; the three types are:
    - .loc()  (label based)
    - .iloc()  (integer based)
    - .ix()    (both label and integer based)
- loc takes two single/list/range operator separated by ','. The first one indicates the row and the second one indicates columns.
- iloc(): Pandas provide various methods in order to get purely integer based indexing. Like python and numpy, these are 0-based indexing.
- ix(): Besides pure label based and integer based, Pandas provides a hybrid method for selections and subsetting the object using the .ix() operator.

#### .loc()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

#select all rows for a specific column
print(df.loc[:,'A'])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
                  index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
                  columns=['X', 'Y', 'Z', 'W'])


selected_column = df.loc[:, 'X']
print(selected_column)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

# Select all rows for multiple columns, say list[]
print(df.loc[:,['A','C']])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
                  index=['apple', 'banana', 'cherry', 'date', 'berry', 'fig', 'grape', 'honeydew'],
                  columns=['X', 'Y', 'Z', 'W'])

selected_columns = df.loc[:, ['X', 'Z']]
print(selected_columns)

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

# Select range of rows for all columns
print(df.loc['a':'h'])

#### .iloc()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# select all rows for a specific column
print(df.iloc[:4])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# Integer slicing

print(df.iloc[1:5, 2:4])

#### .ix()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# Integer slicing
print(df.ix[:4])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A', 'B', 'C', 'D'])

# Integer slicing
print(df.iloc[:5])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
# Index slicing
print(df.ix[:,'A'])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A', 'B', 'C', 'D'])

# Index slicing
print(df.loc[:, 'A'])

## 11.8 Data alignment and arithmetic

 - Data alignment between DataFrame objects automatically align on both the columns and the index (row labels).
 - Again, the resulting object will have the union of the column and row labels.

In [192]:
df1 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df1

          A         B         C         D
0 -2.309901  0.116347  1.376059 -0.283063
1 -0.005518  0.108358  0.461724 -1.077238
2  1.113666 -0.061810  1.610419  1.719797
3 -0.175101  0.420402  0.139519 -0.457722
4  1.911603 -0.544832  0.551447  0.561948
5 -0.609182  1.705093 -0.182868  0.887877
6  0.157782  0.806800 -0.093191 -0.894031
7 -2.124582 -0.015626 -0.507660  0.607992
8 -0.943084  0.466216 -0.001187  1.100966
9 -1.947486  0.167494  1.180974  0.575507

In [199]:
df2 = pd.DataFrame(np.random.randn(10, 4), columns=['X', 'Y', 'Z', 'W'])
df2

          X         Y         Z         W
0 -0.360618  1.900411  2.035637 -3.188815
1  0.870919 -0.369668 -1.219472  0.970874
2  0.124980  0.237941 -0.004469  2.274857
3  0.577515  1.882956 -1.633519 -0.133021
4 -0.014357  0.566124 -1.175657  0.440446
5 -0.166639  0.099598  0.523112 -0.287260
6 -0.183853 -1.081150  0.188342  1.527643
7 -0.052772  0.372040  1.141265 -0.400911
8  0.549215 -0.233944 -0.030225  0.315574
9  0.878235  1.259891 -1.687631 -0.821863

In [205]:
df1+df2

    A   B   C   D   W   X   Y   Z
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN NaN NaN
5 NaN NaN NaN NaN NaN NaN NaN NaN
6 NaN NaN NaN NaN NaN NaN NaN NaN
7 NaN NaN NaN NaN NaN NaN NaN NaN
8 NaN NaN NaN NaN NaN NaN NaN NaN
9 NaN NaN NaN NaN NaN NaN NaN NaN

In [196]:

df3 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
df3

          A         B         C
0 -3.393152 -1.367484  0.694463
1 -0.178713  1.234162 -0.022168
2  0.648453 -1.347807  0.164238
3 -1.678803  1.263623  0.569571
4  0.027914 -0.904488 -0.455166
5  2.125908  0.307436 -0.194773
6 -1.924684  0.136808 -1.371305

In [204]:
df1+df3

          A         B         C   D
0 -5.703052 -1.251136  2.070522 NaN
1 -0.184231  1.342519  0.439556 NaN
2  1.762118 -1.409617  1.774657 NaN
3 -1.853904  1.684025  0.709090 NaN
4  1.939517 -1.449320  0.096281 NaN
5  1.516725  2.012529 -0.377640 NaN
6 -1.766902  0.943607 -1.464496 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

- When doing an operation between DataFrame and Series, the default behavior is to align the Series index on the DataFrame columns, thus broadcasting row-wise. For example:

In [206]:
df1 - df1.iloc[0]

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1  2.304383 -0.007990 -0.914336 -0.794175
2  3.423566 -0.178157  0.234359  2.002860
3  2.134799  0.304055 -1.236540 -0.174659
4  4.221504 -0.661179 -0.824612  0.845011
5  1.700719  1.588746 -1.558927  1.170940
6  2.467683  0.690452 -1.469251 -0.610968
7  0.185319 -0.131973 -1.883719  0.891055
8  1.366817  0.349869 -1.377246  1.384029
9  0.362415  0.051147 -0.195085  0.858570

 - In the special case of working with time series data, and the DataFrame index also contains dates, the broadcasting will be column-wise:

In [207]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=list('ABC'))
df

                   A         B         C
2000-01-01  0.668599  0.677420  0.126167
2000-01-02 -0.598475 -0.025255  0.453342
2000-01-03 -1.897237  0.354735 -0.062378
2000-01-04 -0.459750 -0.538445  1.618713
2000-01-05 -1.682349  0.328723 -3.101858
2000-01-06 -0.056294 -0.303979  0.883465
2000-01-07 -0.026997 -0.186445 -0.436587
2000-01-08  2.257175 -0.942404 -2.657529

In [208]:
df1* 10 + 2

           A          B          C          D
0 -21.099007   3.163471  15.760595  -0.830628
1   1.944819   3.083575   6.617238  -8.772379
2  13.136656   1.381897  18.104187  19.197973
3   0.248986   6.204024   3.395190  -2.577220
4  21.116031  -3.448319   7.514470   7.619480
5  -4.091821  19.050927   0.171324  10.878773
6   3.577821  10.067995   1.068087  -6.940311
7 -19.245820   1.843742  -3.076597   8.079921
8  -7.430838   6.662162   1.988130  13.009665
9 -17.474858   3.674937  13.809741   7.755071

In [209]:
1/df1

            A          B           C         D
0   -0.432919   8.594968    0.726713 -3.532785
1 -181.221672   9.228708    2.165797 -0.928300
2    0.897936 -16.178540    0.620957  0.581464
3   -5.710977   2.378673    7.167481 -2.184732
4    0.523121  -1.835428    1.813411  1.779524
5   -1.641545   0.586478   -5.468436  1.126282
6    6.337856   1.239465  -10.730611 -1.118529
7   -0.470681 -63.996679   -1.969823  1.644758
8   -1.060351   2.144928 -842.469635  0.908293
9   -0.513483   5.970373    0.846759  1.737598

In [ ]:
df1**5

- Boolean operators work as well:

In [210]:
df1 = pd.DataFrame({'a' : [1, 0, 1], 'b' : [0, 1, 1] }, dtype=bool)
df1

       a      b
0   True  False
1  False   True
2   True   True

In [211]:
df2 = pd.DataFrame({'a' : [0, 1, 1], 'b' : [1, 1, 0] }, dtype=bool)
df2

       a      b
0  False   True
1   True   True
2   True  False

In [212]:
df1&df2

       a      b
0  False  False
1  False   True
2   True  False

In [213]:
df1 | df2

      a     b
0  True  True
1  True  True
2  True  True

In [214]:
df1^df2

       a      b
0   True   True
1   True  False
2  False   True

In [215]:
-df1

       a      b
0  False   True
1   True  False
2  False  False

## 11.9 transposing

- To transpose, access the T attribute (also the transpose function), similar to an ndarray:

In [216]:
# only show the first 4 rows
df[:4].T

   2000-01-01  2000-01-02  2000-01-03  2000-01-04
A    0.668599   -0.598475   -1.897237   -0.459750
B    0.677420   -0.025255    0.354735   -0.538445
C    0.126167    0.453342   -0.062378    1.618713

In [217]:
# only show the first 1 row
df[:1].T

   2000-01-01
A    0.668599
B    0.677420
C    0.126167